// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using StockManager.Data.Data;
using StockManager.Data.Data.Entities;
using System;

namespace StockManager.Data.Migrations
{
    [DbContext(typeof(SMContext))]
    [Migration("20190127171103_DeliveryRel3")]
    partial class DeliveryRel3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("StockManager.Data.Data.Entities.Deliveries", b =>
                {
                    b.Property<int>("DeliveryID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Commission");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(16);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<double>("DeliveryCharge");

                    b.Property<DateTime>("DeliveryDate");

                    b.Property<double>("GrossAmount");

                    b.Property<string>("Invoice");

                    b.Property<double>("NetAmount");

                    b.Property<string>("Notes");

                    b.Property<string>("OurRef")
                        .HasMaxLength(30);

                    b.Property<int>("PurchaseOrderID");

                    b.Property<string>("Season")
                        .HasMaxLength(50);

                    b.Property<string>("Shipper")
                        .HasMaxLength(50);

                    b.Property<string>("ShipperInvoice");

                    b.Property<string>("SupplierRef")
                        .HasMaxLength(8);

                    b.Property<int>("TotalBoxes");

                    b.Property<int>("TotalGarments");

                    b.Property<int>("TotalHangers");

                    b.Property<double>("VATAmount");

                    b.Property<string>("WarehouseRef")
                        .HasMaxLength(8);

                    b.HasKey("DeliveryID");

                    b.ToTable("PurchaseOrder");
                });

            modelBuilder.Entity("StockManager.Data.Data.Entities.DelliveryLines", b =>
                {
                    b.Property<int>("DeliveryLinesID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DeliveryID");

                    b.Property<double>("NetAmount");

                    b.Property<int>("QtyBoxes");

                    b.Property<int>("QtyGarments");

                    b.Property<int>("QtyHangers");

                    b.Property<string>("StockCode")
                        .HasMaxLength(30);

                    b.HasKey("DeliveryLinesID");

                    b.HasIndex("DeliveryID")
                        .IsUnique();

                    b.ToTable("PurchaseOrderLines");
                });

            modelBuilder.Entity("StockManager.Data.Data.Entities.Settings", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address1")
                        .HasMaxLength(50);

                    b.Property<string>("Address2")
                        .HasMaxLength(50);

                    b.Property<string>("Address3")
                        .HasMaxLength(50);

                    b.Property<string>("Address4")
                        .HasMaxLength(50);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .HasMaxLength(255);

                    b.Property<string>("PostCode")
                        .HasMaxLength(12);

                    b.Property<string>("Season");

                    b.Property<string>("Telephone")
                        .HasMaxLength(18);

                    b.Property<string>("VATReg")
                        .HasMaxLength(50);

                    b.Property<decimal>("VatRate");

                    b.Property<string>("WWW")
                        .HasMaxLength(255);

                    b.HasKey("CompanyID");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("StockManager.Data.Data.Entities.shopAdjustmentLine", b =>
                {
                    b.Property<int>("ShopAdjustmentLineID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MovementType")
                        .HasMaxLength(50);

                    b.Property<int>("Qty");

                    b.Property<int>("ShopAdjustmentsID");

                    b.Property<string>("StockCode")
                        .HasMaxLength(30);

                    b.Property<decimal>("Values")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ShopAdjustmentLineID");

                    b.ToTable("ShopAdjustmentLines");
                });

            modelBuilder.Entity("StockManager.Data.Data.Entities.shopAdjustments", b =>
                {
                    b.Property<int>("ShopAdjustID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(16);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("MovementDate");

                    b.Property<string>("Reference");

                    b.Property<string>("ShopRef")
                        .HasMaxLength(8);

                    b.Property<int>("TotalGainItems");

                    b.Property<int>("TotalLossItems");

                    b.HasKey("ShopAdjustID");

                    b.ToTable("ShopAdjustment");
                });

            modelBuilder.Entity("StockManager.Data.Data.Entities.shopDeliveries", b =>
                {
                    b.Property<int>("ShopDeliveryID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(16);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("DeliveryDate");

                    b.Property<string>("DeliveryRef")
                        .HasMaxLength(50);

                    b.Property<string>("Notes");

                    b.Property<string>("ShopRef")
                        .IsRequired()
                        .HasMaxLength(8);

                    b.Property<int>("TotHangers");

                    b.Property<string>("WarehouseRef")
                        .IsRequired()
                        .HasMaxLength(8);

                    b.HasKey("ShopDeliveryID");

                    b.ToTable("ShopDelivery");
                });

            modelBuilder.Entity("StockManager.Data.Data.Entities.shopDeliveryLines", b =>
                {
                    b.Property<int>("DeliveryLinesID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("QtyHangers");

                    b.Property<int>("ShopDeliveryID");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("DeliveryLinesID");

                    b.ToTable("ShopDeliveryLine");
                });

            modelBuilder.Entity("StockManager.Data.Data.Entities.shopReturnLines", b =>
                {
                    b.Property<int>("ReturnLineID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Qty");

                    b.Property<int>("ReturnID");

                    b.Property<string>("StockCode")
                        .HasMaxLength(30);

                    b.Property<double>("Value");

                    b.HasKey("ReturnLineID");

                    b.ToTable("ShopReturnLines");
                });

            modelBuilder.Entity("StockManager.Data.Data.Entities.shopReturns", b =>
                {
                    b.Property<int>("ReturnID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(16);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("QtyReturned");

                    b.Property<string>("Reference");

                    b.Property<string>("ShopRef")
                        .HasMaxLength(8);

                    b.Property<DateTime>("TransactionDate");

                    b.Property<string>("WarehouseRef")
                        .HasMaxLength(8);

                    b.HasKey("ReturnID");

                    b.ToTable("ShopReturn");
                });

            modelBuilder.Entity("StockManager.Data.Data.Entities.Shops", b =>
                {
                    b.Property<string>("ShopRef")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8);

                    b.Property<string>("Address1")
                        .HasMaxLength(60);

                    b.Property<string>("Address2")
                        .HasMaxLength(60);

                    b.Property<string>("Address3")
                        .HasMaxLength(60);

                    b.Property<string>("Address4")
                        .HasMaxLength(60);

                    b.Property<string>("ContactName")
                        .HasMaxLength(60);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(16);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Email")
                        .HasMaxLength(60);

                    b.Property<string>("Fax")
                        .HasMaxLength(60);

                    b.Property<string>("Memo");

                    b.Property<string>("PostCode")
                        .HasMaxLength(60);

                    b.Property<int?>("SHopType")
                        .HasMaxLength(60);

                    b.Property<string>("Shopname")
                        .HasMaxLength(60);

                    b.Property<string>("Telephone")
                        .HasMaxLength(60);

                    b.Property<string>("Telephone2")
                        .HasMaxLength(60);

                    b.HasKey("ShopRef");

                    b.ToTable("Shop");
                });

            modelBuilder.Entity("StockManager.Data.Data.Entities.shopTransferLines", b =>
                {
                    b.Property<int>("TransferLineID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CurrentQty");

                    b.Property<string>("StockCode")
                        .HasMaxLength(30);

                    b.Property<int>("TIQty");

                    b.Property<int>("TOQty");

                    b.Property<int>("TransferID");

                    b.HasKey("TransferLineID");

                    b.ToTable("ShopTransferLines");
                });

            modelBuilder.Entity("StockManager.Data.Data.Entities.shopTransfers", b =>
                {
                    b.Property<int>("ShopTransferID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("FromShopRef");

                    b.Property<string>("Reference");

                    b.Property<string>("ToShopRef");

                    b.Property<int>("TotalQtyIn");

                    b.Property<int>("TotalQtyOut");

                    b.Property<DateTime>("TransferDate");

                    b.HasKey("ShopTransferID");

                    b.ToTable("ShopTransfer");
                });

            modelBuilder.Entity("StockManager.Data.Data.Entities.Stock", b =>
                {
                    b.Property<string>("StockCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30);

                    b.Property<double>("AmtTakes");

                    b.Property<double>("CostVal");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(16);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("DeadCode");

                    b.Property<int>("DeliveredQtyHangers");

                    b.Property<string>("Season")
                        .HasMaxLength(60);

                    b.Property<string>("SupplierRef")
                        .HasMaxLength(8);

                    b.Property<bool>("ZeroQty");

                    b.HasKey("StockCode");

                    b.ToTable("Stock");
                });

            modelBuilder.Entity("StockManager.Data.Data.Entities.Suppliers", b =>
                {
                    b.Property<string>("SupplierRef")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8);

                    b.Property<string>("Address1")
                        .HasMaxLength(60);

                    b.Property<string>("Address2")
                        .HasMaxLength(60);

                    b.Property<string>("Address3")
                        .HasMaxLength(60);

                    b.Property<string>("Address4")
                        .HasMaxLength(60);

                    b.Property<string>("ContactName")
                        .HasMaxLength(60);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(16);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Email")
                        .HasMaxLength(60);

                    b.Property<string>("Fax")
                        .HasMaxLength(60);

                    b.Property<string>("Memo");

                    b.Property<string>("PostCode")
                        .HasMaxLength(60);

                    b.Property<string>("SupplierName")
                        .HasMaxLength(60);

                    b.Property<string>("Telephone")
                        .HasMaxLength(60);

                    b.Property<string>("Telephone2")
                        .HasMaxLength(60);

                    b.HasKey("SupplierRef");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("StockManager.Data.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("StockManager.Data.Data.Entities.Warehouse", b =>
                {
                    b.Property<string>("WarehouseRef")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8);

                    b.Property<string>("Address1")
                        .HasMaxLength(60);

                    b.Property<string>("Address2")
                        .HasMaxLength(60);

                    b.Property<string>("Address3")
                        .HasMaxLength(60);

                    b.Property<string>("Address4")
                        .HasMaxLength(60);

                    b.Property<string>("ContactName")
                        .HasMaxLength(60);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(16);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("Default");

                    b.Property<string>("Email")
                        .HasMaxLength(60);

                    b.Property<string>("Fax")
                        .HasMaxLength(60);

                    b.Property<string>("Memo");

                    b.Property<string>("PostCode")
                        .HasMaxLength(60);

                    b.Property<string>("Telephone")
                        .HasMaxLength(60);

                    b.Property<string>("Telephone2")
                        .HasMaxLength(60);

                    b.Property<string>("WarehouseName")
                        .HasMaxLength(60);

                    b.Property<int?>("WarehouseType");

                    b.HasKey("WarehouseRef");

                    b.ToTable("Warehouse");
                });

            modelBuilder.Entity("StockManager.Data.Data.Entities.WarehouseAdjustmentLines", b =>
                {
                    b.Property<int>("WarehouseAdjustmentLineID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MovementType")
                        .HasMaxLength(50);

                    b.Property<int>("Qty");

                    b.Property<string>("StockCode")
                        .HasMaxLength(30);

                    b.Property<double>("Values");

                    b.Property<int>("WarehouseAdjustmentsID");

                    b.HasKey("WarehouseAdjustmentLineID");

                    b.ToTable("WarehouseAdjustmentLines");
                });

            modelBuilder.Entity("StockManager.Data.Data.Entities.WarehouseAdjustments", b =>
                {
                    b.Property<int>("WarehouseAdjustID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(16);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("MovementDate");

                    b.Property<string>("Reference");

                    b.Property<int>("TotalGainItems");

                    b.Property<int>("TotalLossItems");

                    b.Property<string>("WarehouseRef")
                        .HasMaxLength(8);

                    b.HasKey("WarehouseAdjustID");

                    b.ToTable("WarehouseAdjustment");
                });

            modelBuilder.Entity("StockManager.Data.Data.Entities.WarehouseReturn", b =>
                {
                    b.Property<int>("WarehouseReturnID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("FromWarehouseRef")
                        .HasMaxLength(8);

                    b.Property<string>("Reference");

                    b.Property<DateTime>("ReturnDate");

                    b.Property<string>("ToWarehouseRef")
                        .HasMaxLength(8);

                    b.Property<int>("TotalBoxesQty");

                    b.Property<int>("TotalGarmentsQty");

                    b.Property<int>("TotalUnitsQty");

                    b.HasKey("WarehouseReturnID");

                    b.ToTable("WarehouseReturn");
                });

            modelBuilder.Entity("StockManager.Data.Data.Entities.WarehouseReturnLines", b =>
                {
                    b.Property<int>("WarehouseReturnLineID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CurrentQtyBoxes");

                    b.Property<int>("CurrentQtyGarments");

                    b.Property<int>("CurrentQtyUnits");

                    b.Property<int>("ReturnID");

                    b.Property<int>("ReturnQtyBoxes");

                    b.Property<int>("ReturnQtyGarments");

                    b.Property<int>("ReturnQtyUnits");

                    b.Property<string>("StockCode")
                        .HasMaxLength(8);

                    b.HasKey("WarehouseReturnLineID");

                    b.ToTable("WarehouseReturnLines");
                });

            modelBuilder.Entity("StockManager.Data.Data.Entities.WarehouseTransferLines", b =>
                {
                    b.Property<int>("WarehouseTransferLineID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("StockCode")
                        .HasMaxLength(30);

                    b.Property<int>("TOQtyBoxes");

                    b.Property<int>("TOQtyGarments");

                    b.Property<int>("TOQtyUnits");

                    b.Property<int>("WarehouseTransferID");

                    b.HasKey("WarehouseTransferLineID");

                    b.ToTable("WarehouseTransferLines");
                });

            modelBuilder.Entity("StockManager.Data.Data.Entities.WarehouseTransfers", b =>
                {
                    b.Property<int>("WarehouseTransferID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(16);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("FromWarehouseRef")
                        .HasMaxLength(8);

                    b.Property<string>("Reference");

                    b.Property<string>("ToWarehouseRef")
                        .HasMaxLength(8);

                    b.Property<int>("TotalBoxesQtyIn");

                    b.Property<int>("TotalBoxesQtyOut");

                    b.Property<int>("TotalGarmentsQtyIn");

                    b.Property<int>("TotalGarmentsQtyOut");

                    b.Property<int>("TotalUnitsQtyIn");

                    b.Property<int>("TotalUnitsQtyOut");

                    b.Property<DateTime>("TransferDate");

                    b.HasKey("WarehouseTransferID");

                    b.ToTable("WarehouseTransfer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("StockManager.Data.Data.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("StockManager.Data.Data.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StockManager.Data.Data.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("StockManager.Data.Data.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StockManager.Data.Data.Entities.DelliveryLines", b =>
                {
                    b.HasOne("StockManager.Data.Data.Entities.Deliveries")
                        .WithOne("deliveryLines")
                        .HasForeignKey("StockManager.Data.Data.Entities.DelliveryLines", "DeliveryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
